export const routeConstants = {
    LOGIN: '/signin',
    SIGN_UP: '/signup',
    HOME: '/',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    NOT_FOUND: '/error-404',
    SERVER_ERROR: '/500',
    UNAUTHORIZED: '/401',
    FORBIDDEN: '/403',
    LOGOUT: '/logout',
    RESET_PASSWORD: '/reset-password',
    PARTIES: '/parties',
    CREATE_PARTIES: (partyId : string | null) => `/parties/create` + (partyId ? `/${partyId}` : '/:id'),
    EDIT_PARTIES: (partyId : string | null) => `/parties/edit` + (partyId ? `/${partyId}` : '/:id'),
    PARTY_TRANSACTION: '/party/transaction',
    ITEMS: '/items',
    CREATE_ITEMS: (itemId : string | null) => `/items/create` + (itemId ? `/${itemId}` : '/:id'),
    EDIT_ITEMS: (itemId : string | null) => `/items/edit` + (itemId ? `/${itemId}` : '/:id'),
    REPORTS: '/reports',
    CASH_AND_BANK: '/cash-and-bank',
    EXPENSES: '/expenses',
    POS: 'pos-billing',
    SETTING: 'settings',
    SALES_INVOICE: '/sales-invoice',
    CREATE_SALES_INVOICE: (invoiceId: string | null) => `/sales-invoice/create`+ (invoiceId ? `/${invoiceId}` : '/:id'),
    SALES_INVOICE_DETAILS: (invoiceId: string | null) => `/sales-invoice/details`+ (invoiceId ? `/${invoiceId}` : '/:id'),
    QUOTATION_ESTIMATE: '/quotation-estimate',
    CREATE_QUOTATION_INVOICE: (invoiceId: string | null) => `/quotation-estimate/create`+ (invoiceId ? `/${invoiceId}` : '/:id'),
    QUOTATION_INVOICE_DETAILS: (invoiceId: string | null) => `/quotation-estimate/details`+ (invoiceId ? `/${invoiceId}` : '/:id'),
    PAYMENT_IN: '/payment-in',
    CREATE_PAYMENT_IN: (id: string | null) => `/payment-in/create`+ (id ? `/${id}` : '/:id'),
    PAYMENT_IN__DETAILS: (id: string | null) => `/payment-in/details`+ (id ? `/${id}` : '/:id'),
    SALES_RETURN: '/sales-return',
    CREATE_SALES_RETURN: (id: string | null) => `/sales-return/create`+ (id ? `/${id}` : '/:id'),
    SALES_RETURN_DETAILS: (id: string | null) => `/sales-return/details`+ (id ? `/${id}` : '/:id'),
    PURCHASE_INVOICE: '/purchase-invoice',
    CREATE_PURCHASE_INVOICE: (invoiceId: string | null) => `/purchase-invoice/create`+ (invoiceId ? `/${invoiceId}` : '/:id'),
    PURCHASE_INVOICE_DETAILS: (invoiceId: string | null) => `/purchase-invoice/details`+ (invoiceId ? `/${invoiceId}` : '/:id'),
    PURCHASE_RETURN: '/purchase-return',
    PAYMENT_OUT: '/payment-out',
}