export const routeConstants = {
    LOGIN: '/signin',
    SIGN_UP: '/signup',
    HOME: '/',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    NOT_FOUND: '/error-404',
    SERVER_ERROR: '/500',
    UNAUTHORIZED: '/401',
    FORBIDDEN: '/403',
    LOGOUT: '/logout',
    RESET_PASSWORD: '/reset-password',
    PARTIES: '/parties',
    CREATE_PARTIES: (partyId : string | null) => `/parties/create` + (partyId ? `/${partyId}` : '/:id'),
    EDIT_PARTIES: (partyId : string | null) => `/parties/edit` + (partyId ? `/${partyId}` : '/:id'),
    PARTY_TRANSACTION: '/party/transaction',
    ITEMS: '/items',
    REPORTS: '/reports',
    CASH_AND_BANK: '/cash-and-bank',
    EXPENSES: '/expenses',
    POS: 'pos-billing',
    SETTING: 'settings',
    SALES_INVOICE: '/sales-invoice',
    QUOTATION_ESTIMATE: '/quotation-estimate',
    PAYMENT_IN: '/payment-in',
    SALES_RETURN: '/sales-return',
    PURCHASE_INVOICE: '/purchase-invoice',
    PURCHASE_RETURN: '/purchase-return',
    PAYMENT_OUT: '/payment-out',
}